### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by jzhang-0** [amalrajan/learncpp-download#15]
log is following:

> (download_file pid=70080) ERROR:root:unable to download: http://www.learncpp.com/cpp-tutorial/introduction-to-these-tutorials#FAQ
(download_file pid=70080) ERROR:root:unable to download: https://www.learncpp.com/cpp-tutorial/configuring-your-compiler-compiler-extensions/
(download_file pid=70081) ERROR:root:unable to download: https://www.learncpp.com/cpp-tutorial/introduction-to-cplusplus/
(download_file pid=70081) ERROR:root:unable to download: https://www.learncpp.com/cpp-tutorial/configuring-your-compiler-warning-and-error-levels/
(download_file pid=70081) ERROR:root:unable to download: https://www.learncpp.com/cpp-tutorial/introduction-to-iostream-cout-cin-and-endl/
(download_file pid=70084) ERROR:root:unable to download: https://www.learncpp.com/cpp-tutorial/installing-an-integrated-development-environment-ide/
(download_file pid=70084) ERROR:root:unable to download: https://www.learncpp.com/cpp-tutorial/comments/
(download_file pid=70084) ERROR:root:unable to download: https://www.learncpp.com/cpp-tutorial/introduction-to-expressions/
(download_file pid=70083) ERROR:root:unable to download: http://www.learncpp.com/cpp-tutorial/introduction-to-these-tutorials#FAQ
(download_file pid=70083) ERROR:root:unable to download: https://www.learncpp.com/cpp-tutorial/compiling-your-first-program/

**Comment by amalrajan** [comment]
@jzhang-0 you need wkhtmltopdf installed 

https://wkhtmltopdf.org/downloads.html
