### ISSUE TITLE
OSError: cannot load library 'gobject-2.0-0'

### ISSUE THREAD

**Issue by generalpy101** [amalrajan/learncpp-download#23]
Hello,
I think your program is not working for python versions 3.8 and above.

Weasy print is giving errror on import.
![image](https://user-images.githubusercontent.com/48615112/176078135-ceda98f6-2116-460d-bad9-2aa16baa6a84.png)

I found a possible solution : https://stackoverflow.com/questions/63449770/oserror-cannot-load-library-gobject-2-0-error-0x7e
But for this solution I have to download GTK. Is there a way I can use it without GTK?

My Python version is 3.9.7.

**Comment by quinnjbrooks** [comment]
same with me... python 3.10, its unusable

**Comment by amalrajan** [comment]
Closing this issue, as it's not longer valid
