### ISSUE TITLE
Exits at 90% with no message and nothing downloaded?

### ISSUE THREAD

**Issue by p0358** [amalrajan/learncpp-download#33]
```
$ docker run --rm --name=learncpp-download -v learncpp-download:/app/downloads --shm-size=10.17gb amalrajan/learncpp-download
[======================================================------] 90.0% ...
```
It just exits after it gets to 90% (where it gets pretty much instantly), then it just exists. The mounted folder for download is empty, and it *seems* to be exiting with exit code 0

**Comment by amalrajan** [comment]
Thanks for bringing this up, fixed. On a side note, it's way faster if you run it locally.

**Comment by p0358** [comment]
Thanks for the prompt fix. Hmm, this time around it seems to have gotten to 99.7%, and then it was doing something with around 100% CPU usage for 1 minute and 45 seconds, then exited but it did seemingly download the files at a glance (except 001?). However there is also one more issue:
![image](https://github.com/amalrajan/learncpp-download/assets/5182588/e6ebc89d-4d4f-4503-b26d-5690e5a7dc42)
All pages have the cookie notice :D

**Comment by amalrajan** [comment]
Closing this issue, as it's not longer valid
