### ISSUE TITLE
doesn't download

### ISSUE THREAD

**Issue by mohammadRezaeian** [amalrajan/learncpp-download#38]
hi 
thank you for write this software 
but i have a problem:
it doesn't download anything and only displays this output
and just create directory downloads

`2023-10-15 09:11:30,546 INFO worker.py:1636 -- Started a local Ray instance.`

**Comment by mohammadRezaeian** [comment]
but docker work

**Comment by AbelHutten** [comment]
Same for me.

**Comment by amalrajan** [comment]
@mohammadRezaeian @AbelHutten check if you have "wkhtmltopdf" installed. It's a core dependency

**Comment by amalrajan** [comment]
Closing this issue, as it's not longer valid
