### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by ArmynC** [amalrajan/learncpp-download#39]
```
(process:18596): GLib-GIO-WARNING **: 21:51:57.865: Unexpectedly, UWP app `Microsoft.ScreenSketch_11.2309.16.0_x64__8wekyb3d8bbwe' (AUMId `Microsoft.ScreenSketch_8wekyb3d8bbwe!App') supports 29 extensions but has no verbs

(process:18596): GLib-GIO-WARNING **: 21:51:57.909: Unexpectedly, UWP app `Clipchamp.Clipchamp_2.8.1.0_neutral__yxz26nhyzhsrt' (AUMId `Clipchamp.Clipchamp_yxz26nhyzhsrt!App') supports 41 extensions but has no verbs
```

It stops at 99.7%.

Empty **Download** folder.

**Comment by Natee9969** [comment]
(process:18596): GLib-GIO-WARNING **: 21:51:57.865: Unexpectedly, UWP app `Microsoft.ScreenSketch_11.2309.16.0_x64__8wekyb3d8bbwe' (AUMId `Microsoft.ScreenSketch_8wekyb3d8bbwe!App') supports 29 extensions but has no verbs

(process:18596): GLib-GIO-WARNING **: 21:51:57.909: Unexpectedly, UWP app `Clipchamp.Clipchamp_2.8.1.0_neutral__yxz26nhyzhsrt' (AUMId `Clipchamp.Clipchamp_yxz26nhyzhsrt!App') supports 41 extensions but has no verbs

**Comment by amalrajan** [comment]
Are you by any chance using python from windows store? If so, I would recommend getting the one from [https://www.python.org/](https://www.python.org/)

**Comment by ArmynC** [comment]
I had one version (3.12) installed earlier but since the requirement was 3.10, I downloaded version the bin from the official website.

```Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32```

_Windows 11 Pro_

**Comment by amalrajan** [comment]
Looks like this breaks on windows. For now you can stick with WSL2 or Docker if you are using Windows. If you're feeling adventurous however, you can play around with the source code and remove those dependencies which are causing it to fail :)

**Comment by amalrajan** [comment]
Closing this issue, as it's fixed now
