### ISSUE TITLE
Bot doesn't scrape images

### ISSUE THREAD

**Issue by GlassOfAnarchy** [amalrajan/learncpp-download#45]
It would be nice if it also scraped screenshots, currrently it just leaves empty spaces...
![Screenshot 2024-01-28 104702](https://github.com/amalrajan/learncpp-download/assets/70875007/2b819827-4d0d-43f1-a768-584968350f90)
![Screenshot 2024-01-28 105057](https://github.com/amalrajan/learncpp-download/assets/70875007/462c8a9a-5997-4bdc-93d4-06cdf295f291)
![Screenshot 2024-01-28 105124](https://github.com/amalrajan/learncpp-download/assets/70875007/81a3144a-715c-4354-9329-1341b269dbe2)
![Screenshot 2024-01-28 105150](https://github.com/amalrajan/learncpp-download/assets/70875007/5da0b75c-091c-4415-8ea2-b7c5ae899ccf)
![Screenshot 2024-01-28 105159](https://github.com/amalrajan/learncpp-download/assets/70875007/a8b16e0a-e5db-4edb-9728-8edcf359d1bb)
![Screenshot 2024-01-28 105213](https://github.com/amalrajan/learncpp-download/assets/70875007/46e60dae-60a7-4b68-b652-315cd6d51a0a)
![Screenshot 2024-01-28 105232](https://github.com/amalrajan/learncpp-download/assets/70875007/d2515dc7-9f12-4a3e-8bc1-8f7414640774)
![Screenshot 2024-01-28 1051241](https://github.com/amalrajan/learncpp-download/assets/70875007/4cb9b80a-0c3e-4f3a-8768-511e8ac8264c)
![Screenshot 2024-01-28 1051591](https://github.com/amalrajan/learncpp-download/assets/70875007/f7239694-02c0-4c4b-9624-c9e7228f7aac)
![Screenshot 2024-01-28 1052131](https://github.com/amalrajan/learncpp-download/assets/70875007/965ec27d-3e61-4deb-abc8-76075a933e8e)
![Screenshot 2024-01-28 1052321](https://github.com/amalrajan/learncpp-download/assets/70875007/f620c660-0b60-4a16-ad3e-db0c5fefec14)

**Comment by amalrajan** [comment]
good catch, sir. Much appreciated

**Comment by amalrajan** [comment]
Closing this one, as it's fixed with the latest build. Feel free to open a new thread if you face any difficulty
