### ISSUE TITLE
What is the step after installing wkhtmlpdf?

### ISSUE THREAD

**Issue by birajkhadka** [amalrajan/learncpp-download#6]
Is the step after wkhtmlpdf: python3 main.py [-h] [-o OUTPUT] [--nopdf] or something else?
I have run wkhtmlpdf application but it just opens for a certain instant.

**Comment by jerry048** [comment]
just run `python3 main.py` but this script won't work no more because the site got updated. You can check out my pull request if you are still interested.

**Comment by boyuuan** [comment]
@jerry048 using your PR will it work? if so which branch?

**Comment by jerry048** [comment]
@boyuuan 
https://github.com/jerry048/learncpp-download

**Comment by boyuuan** [comment]
@jerry048 Thank you!

**Comment by amalrajan** [comment]
The script is updated, you can simply execute `python3 main.py`
